### ISSUE TITLE
Arisutea plate compatibility

### ISSUE THREAD

**Issue by ctlrome** [mattyams/arisutea-pcb#3]
Is the arisutea plate compatible with the arisu case?

**Comment by mattyams** [comment]
I haven't forgotten about this, just waiting on the extra acrylic case to show up this week so I can test it without having to disassemble my current board that is already built.

**Comment by ctlrome** [comment]
Sorry for the bombardment of questions, but does the PCB mount to the plate
in any way (besides the switches). I had some hotswap boards that fell from
under the switches since nothing else was holding them together.

**Comment by mattyams** [comment]
No worries! So the case came in and I confirmed that the FR4 plate does fit above the PCB and under the acrylic switch plate, however, the 3mm thickness of the acrylic switch plate renders the FR4 plate useless.  The FR4 plate makes no contact with the switches nor will provide any further "support" to PCB or otherwise.

BUT! During the assembly of the Arisutea PCB into the Arisutea acrylic case I observed that adding the hot swap sockets to the PCB adds some height to the PCB itself which in turn allows the PCB to rest comfortably on the bottom acrylic plate and is not floating like I had previously thought it would once switches are inserted into the case and PCB.

I hope this helps and answers your question. Please feel free to inquire further if you have anymore questions.

**Comment by ctlrome** [comment]
Thank you so much! I was thinking about getting a couple of arisutea PCBs
and plates, but I'm gonna wait until you release the final version. Keep up
the good work!

**Comment by mattyams** [comment]
So I did a little more work on this and found that when I was originally testing this for you that I did not have all the pieces in place for the hipro case. You can do this however the hardware changes (standoffs need to be shorter) and the case is a 3mm shorter. If you don't want to do that then get some of this foam (https://smile.amazon.com/gp/product/B07BL296HK/) or something similar in 2mm or 3mm and use the PCB as a template to cut a piece to place under the PCB in the case. This will do 2 things. 1. It will help with acoustics and 2. It will assist in PCB support when installing/replacing switches after assembly.

**Comment by ctlrome** [comment]
That’s convenient since I ordered a bunch of eva foam from ponoko with the
case so I’ll just use that. Thanks for letting me know.
